/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import javax.swing.JOptionPane;
import negocio.*;
import java.text.NumberFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gabriel Lossada
 */
public class FrmBalanceDiario extends javax.swing.JInternalFrame {

    private final MovimientosControl CTRLM;
    private String accion;
    private String Inversion;
    private float Dolar;
    private String nomAnt;
    private int idPrestamoActual;
    private double montoApagarActual;
    public DefaultTableModel modeloDetalle;
    Locale locale;      
    NumberFormat currencyFormatter;

    //paginacion
    private int totalXPag = 10;
    private int numPag = 1;
    private int totalRegistros;

    public FrmBalanceDiario() {
        initComponents();
        this.CTRLM = new MovimientosControl();
        locale = new Locale("es", "MX");
        currencyFormatter = NumberFormat.getCurrencyInstance(locale);

        this.primeraCarga();
        this.cargarMontos();
    }

    
    public void cargarMontos(){
        double montoCalle=CTRLM.sumGanancia("S")-CTRLM.sumMonto("E");
        double montoDisp=CTRLM.sumMonto("I")-CTRLM.sumMonto("S")+CTRLM.sumMonto("E");
        
        txtDineroCalle.setText("$"+String.valueOf(currencyFormatter.format(montoCalle)));
        txtDineroDisp.setText("$"+String.valueOf(currencyFormatter.format(montoDisp)));
    }
    
    public void ocultarColumnaPrestamos() {
        tblVentas.getColumnModel().getColumn(1).setMaxWidth(0);
        tblVentas.getColumnModel().getColumn(1).setMinWidth(0);
        tblVentas.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
        tblVentas.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);

        tblVentas.getColumnModel().getColumn(0).setMaxWidth(0);
        tblVentas.getColumnModel().getColumn(0).setMinWidth(0);
        tblVentas.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblVentas.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

    }
    



    public void listar(String dia, String mes, String año) {
        
        tblVentas.setModel(this.CTRLM.listarDiario(dia,mes,año));
        

        TableRowSorter orden = new TableRowSorter(tblVentas.getModel());
        tblVentas.setRowSorter(orden);
//      this.ocultarColumnaPrestamos();
        lblRegistros.setText("Mostrando: " + CTRLM.totalMostrados() + " registros de " + CTRLM.totalReg() + " registros.");
    }
    


    private void limpiar() {
        
    }

    private void mjeError(String mje) {
        JOptionPane.showMessageDialog(this, mje, "Sistema", JOptionPane.ERROR_MESSAGE);
    }

    private void mjeOK(String mje) {
        JOptionPane.showMessageDialog(this, mje, "Sistema", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void primeraCarga (){
    LocalDate hoy = LocalDate.now();
    String fecha= hoy.format(DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT));
    String[] part=fecha.split("/");
    String dia=part[0];
    String mes=part[1];
    String año=part[2];
    txtDia.setText(dia);
    txtMes.setText(mes);
    txtYear.setText(año);
        
        
        this.listar(dia, mes, año);
        double ganancia =CTRLM.getGananciaPD("E", dia, mes, año);
        double salida = CTRLM.getMontoPD("S", dia, mes, año);
        double entrada = CTRLM.getMontoPD("E", dia, mes, año);
        txtGanancia.setText(String.valueOf(currencyFormatter.format(ganancia)));
        txtSalidaXmes.setText(String.valueOf(currencyFormatter.format(salida)));
        txtEntradaXmes.setText(String.valueOf(currencyFormatter.format(entrada)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        lblRegistros = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtGanancia = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDineroCalle = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDineroDisp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSalidaXmes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEntradaXmes = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Movimientos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/images/consultas.png"))); // NOI18N

        tblVentas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblVentas);

        lblRegistros.setText("Registros");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Buscar fecha:");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("/");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ganancia del dia:");

        txtGanancia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGanancia.setForeground(new java.awt.Color(0, 153, 102));
        txtGanancia.setText("$0.00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Dinero en calle:");

        txtDineroCalle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDineroCalle.setForeground(new java.awt.Color(204, 0, 51));
        txtDineroCalle.setText("$0.00");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Dinero disponible:");

        txtDineroDisp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDineroDisp.setForeground(new java.awt.Color(0, 0, 204));
        txtDineroDisp.setText("$0.00");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Salidas:");

        txtSalidaXmes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSalidaXmes.setForeground(new java.awt.Color(204, 0, 51));
        txtSalidaXmes.setText("$0.00");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Entrada:");

        txtEntradaXmes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEntradaXmes.setForeground(new java.awt.Color(0, 0, 204));
        txtEntradaXmes.setText("$0.00");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("/");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Dia");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Mes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Año");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(647, Short.MAX_VALUE)
                .addComponent(lblRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtGanancia))
                        .addGap(129, 129, 129)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtSalidaXmes))
                        .addGap(129, 129, 129)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEntradaXmes)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel15))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDineroDisp)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11)
                    .addComponent(txtDineroCalle))
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jButton4)
                            .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDineroDisp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGanancia)
                    .addComponent(txtDineroCalle)
                    .addComponent(txtSalidaXmes)
                    .addComponent(txtEntradaXmes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelVentas.addTab("Movimientos diarios", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                if(txtMes.getText().isBlank()){
                        this.mjeError("debe ingresar mes valido");
                        return;
                    }
                if(txtYear.getText().isBlank()){
                        this.mjeError("debe ingresar año valido");
                        return;
                    }
        
        this.listar(txtDia.getText(), txtMes.getText(), txtYear.getText());
        double ganancia =CTRLM.getGananciaPD("E", txtDia.getText(), txtMes.getText(), txtYear.getText());
        double salida = CTRLM.getMontoPD("S", txtDia.getText(), txtMes.getText(), txtYear.getText());
        double entrada = CTRLM.getMontoPD("E", txtDia.getText(), txtMes.getText(), txtYear.getText());
        txtGanancia.setText(String.valueOf(currencyFormatter.format(ganancia)));
        txtSalidaXmes.setText(String.valueOf(currencyFormatter.format(salida)));
        txtEntradaXmes.setText(String.valueOf(currencyFormatter.format(entrada)));
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRegistros;
    private javax.swing.JTabbedPane panelVentas;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtDia;
    private javax.swing.JLabel txtDineroCalle;
    private javax.swing.JLabel txtDineroDisp;
    private javax.swing.JLabel txtEntradaXmes;
    private javax.swing.JLabel txtGanancia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JLabel txtSalidaXmes;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
