/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

import entidades.PrestamoMensual;
import java.text.NumberFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import negocio.*;

/**
 *
 * @author Gabriel Lossada
 */
public class FrmCancelarPrestamoQ extends javax.swing.JDialog {

   public FrmPrestamosQ vista;
    private final PrestamoControlQuincenal CTRL;
    private final MovimientosControl CTRLM;
    private String nomAnt;
    private int idCliente;
    private int idPrestamo;
    private double valorTotal;
    private String fechaFin;
    String cliente;
    LocalDate hoy = LocalDate.now();
    //paginacion
    
    
    public FrmCancelarPrestamoQ(java.awt.Frame parent, FrmPrestamosQ frm, boolean modal,int idPrestamo,int idCliente, String cliente) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.vista=frm;
        this.setTitle("Pagar cuota");
        this.CTRL = new PrestamoControlQuincenal();
        this.CTRLM = new MovimientosControl();
        this.idCliente=idCliente;
        this.cliente = cliente;
        this.idPrestamo=idPrestamo;
        this.fechaFin=this.hoy.format(DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT));
        this.valorTotal=Variables.roundUp(this.calcularValotCancelar(this.idPrestamo),100);
        this.cargarCampos();
        
        this.setVisible(true);
    }
    
    private void cargarCampos(){
        txtValorCancelar.setText(Double.toString(this.valorTotal));
    }
    
    private double calcularValotCancelar(int idPrestamo){
        int cantCuotas=CTRL.cantCuotas(idPrestamo);
        int cantCuotasPagadas=CTRL.cantCuotasPagadas(idPrestamo);
        double monto = CTRL.montoPrestado(idPrestamo);
        double total=0;
        double interes=CTRL.getInteres(idPrestamo)/100;
        if(interes==0){
            interes=0.11;
        }
        for (int i = 0; i <= cantCuotasPagadas; i++) {
            total+=((monto/(cantCuotasPagadas+1))-(monto/cantCuotas))*Math.pow((1+interes),i);
            
        }
        total+=CTRL.valorCuota(idPrestamo, cantCuotasPagadas+1);
        return Math.ceil(total);
    }
    
    private void mjeError(String mje) {
        JOptionPane.showMessageDialog(this, mje, "Sistema", JOptionPane.ERROR_MESSAGE);
    }

    private void mjeOK(String mje) {
        JOptionPane.showMessageDialog(this, mje, "Sistema", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtValorCancelar = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total a pagar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtValorCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double totalPagado = Double.parseDouble(txtValorCancelar.getText()) + CTRL.sumarCuotasEstado(this.idPrestamo, "Pagado");
        double gananciaTotal=totalPagado - CTRL.montoPrestado(idPrestamo);
        double gananciaCancel=gananciaTotal-CTRL.sumarGananciaEstado(idPrestamo, "Pagado");
        String fecha=this.fechaFin;
        String[] part=fecha.split("/");
        String dia = part[0];
        String mes = part[1];
        String año = part[2];
        CTRL.setFechaFinPrestamoCancelar(this.fechaFin, this.idPrestamo);
        CTRL.setEstadoPrestamo("Finalizado", this.idPrestamo);
        CTRLM.insertar(this.idCliente, this.cliente, "Prestamo Cancelado", Double.parseDouble(txtValorCancelar.getText()), gananciaCancel, dia, mes, año, "E");
        String resp = CTRL.setTotalPagar(this.idPrestamo, totalPagado);
        String resp2 = CTRL.editarCuotaEstado("Pagado", this.idPrestamo, "a pagar");
        String resp3 = CTRL.setProxCuota("1", this.idPrestamo);
        if (resp.equals("OK") && resp2.equals("OK") && resp3.equals("OK")) {
            this.mjeOK("Prestamo cancelado por monto " + txtValorCancelar.getText());
            this.setVisible(false);
        } else {
            this.mjeError("error al cancelar prestamo");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtValorCancelar;
    // End of variables declaration//GEN-END:variables
}
