/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import negocio.*;
import entidades.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gabriel Lossada
 */
public class FrmResumen extends javax.swing.JInternalFrame {

    private int vencidosM;
    private int porvencerM;
    private int venceHoyM;
        
    private int vencidosQ;
    private int porvencerQ;
    private int venceHoyQ;
    

    public FrmResumen(int vencidosM, int porvencerM, int venceHoyM, int vencidosQ, int porvencerQ, int venceHoyQ) {
        initComponents();
        this.vencidosM=vencidosM;
        this.porvencerM=porvencerM;
        this.venceHoyM=venceHoyM;
        this.vencidosQ=vencidosQ;
        this.porvencerQ=porvencerQ;
        this.venceHoyQ=venceHoyQ;
        this.cargarMensajes();
    }

   
    public void cargarMensajes(){
        lblVencidosM.setText("Vencidos: " + Integer.toString(this.vencidosM));
        lblVenceHoyM.setText("Vencen Hoy: " + Integer.toString(this.venceHoyM));
        lblVenceProntoM.setText("Vencen pronto: " + Integer.toString(this.porvencerM));
        
        lblVencidosQ.setText("Vencidos: " + Integer.toString(this.vencidosQ));
        lblVenceHoyQ.setText("Vencen Hoy: " + Integer.toString(this.venceHoyQ));
        lblVenceProntoQ.setText("Vencen pronto: " + Integer.toString(this.porvencerQ));
    }
    
    private void mjeError(String mje) {
        JOptionPane.showMessageDialog(this, mje, "Sistema", JOptionPane.ERROR_MESSAGE);
    }

    private void mjeOK(String mje) {
        JOptionPane.showMessageDialog(this, mje, "Sistema", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblVencidosM = new javax.swing.JLabel();
        lblVenceHoyM = new javax.swing.JLabel();
        lblVenceProntoM = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblVencidosQ = new javax.swing.JLabel();
        lblVenceProntoQ = new javax.swing.JLabel();
        lblVenceHoyQ = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jButton5.setText("Ver detalle");

        jButton7.setText("Ver detalle");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resumen");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Creditos mensuales:");

        lblVencidosM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVencidosM.setForeground(new java.awt.Color(204, 0, 0));
        lblVencidosM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVencidosM.setText("Vencidos:");

        lblVenceHoyM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVenceHoyM.setForeground(new java.awt.Color(255, 102, 0));
        lblVenceHoyM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVenceHoyM.setText("Vencen hoy:");

        lblVenceProntoM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVenceProntoM.setForeground(new java.awt.Color(0, 0, 204));
        lblVenceProntoM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVenceProntoM.setText("Vencen pronto:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Creditos quincenales:");

        lblVencidosQ.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVencidosQ.setForeground(new java.awt.Color(204, 0, 0));
        lblVencidosQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVencidosQ.setText("Vencidos:");

        lblVenceProntoQ.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVenceProntoQ.setForeground(new java.awt.Color(0, 0, 204));
        lblVenceProntoQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVenceProntoQ.setText("Vencen pronto:");

        lblVenceHoyQ.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVenceHoyQ.setForeground(new java.awt.Color(255, 102, 0));
        lblVenceHoyQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVenceHoyQ.setText("Vencen hoy:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Ver detalle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Ver detalle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Ver detalle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Ver detalle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Ver detalle");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setText("Ver detalle");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVencidosM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVenceProntoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVenceHoyM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVencidosQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVenceHoyQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVenceProntoQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(226, 226, 226))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 237, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(222, 222, 222))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVencidosM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVenceHoyM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVenceProntoM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVencidosQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVenceHoyQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVenceProntoQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame frame = new JFrame();
        FrmPrestamosM frm = new FrmPrestamosM(frame,"v");
        FrmPrincipal.escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFrame frame = new JFrame();
        FrmPrestamosM frm = new FrmPrestamosM(frame,"vh");
        FrmPrincipal.escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame frame = new JFrame();
        FrmPrestamosM frm = new FrmPrestamosM(frame,"vp");
        FrmPrincipal.escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFrame frame = new JFrame();
        FrmPrestamosQ frm = new FrmPrestamosQ(frame,"v");
        FrmPrincipal.escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFrame frame = new JFrame();
        FrmPrestamosQ frm = new FrmPrestamosQ(frame,"vh");
        FrmPrincipal.escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFrame frame = new JFrame();
        FrmPrestamosQ frm = new FrmPrestamosQ(frame,"vp");
        FrmPrincipal.escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblVenceHoyM;
    private javax.swing.JLabel lblVenceHoyQ;
    private javax.swing.JLabel lblVenceProntoM;
    private javax.swing.JLabel lblVenceProntoQ;
    private javax.swing.JLabel lblVencidosM;
    private javax.swing.JLabel lblVencidosQ;
    // End of variables declaration//GEN-END:variables
}
