/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import negocio.*;

/**
 *
 * @author Gabriel Lossada
 */
public class FrmSelecClienteM extends javax.swing.JDialog {

   public FrmPrestamosM vista;
    private final ClienteControl CTRL;
    private String nomAnt;
    private String accion;
    //paginacion
    private int totalXPag = 10;
    private int numPag = 1;
    private boolean primeraCarga = true;
    private int totalRegistros;
    
    
    public FrmSelecClienteM(java.awt.Frame parent, FrmPrestamosM frm, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.vista=frm;
        this.setTitle("Seleccionar Cliente");
        this.CTRL = new ClienteControl();
        this.accion = "guardar";
        this.paginar();
        this.listar("",false);
        this.primeraCarga=false;
        
        
        this.setVisible(true);
    }
    
        public void paginar(){
        int totalPaginas;
        
        this.totalRegistros=this.CTRL.totalReg();
        this.totalXPag=Integer.parseInt((String)cboTotalXPag.getSelectedItem());
        totalPaginas=(int)(Math.ceil((double)this.totalRegistros/this.totalXPag));
        if(totalPaginas==0){
            totalPaginas=1;
        }
        cboNumPag.removeAllItems();
        for (int i = 1; i <= totalPaginas; i++) {
            cboNumPag.addItem(Integer.toString(i));
        }
        cboNumPag.setSelectedIndex(0);
    }

    public void listar(String text, boolean paginar) {
        this.totalXPag= Integer.parseInt((String)cboTotalXPag.getSelectedItem());
        if((String)cboNumPag.getSelectedItem()!=null){
            this.numPag=Integer.parseInt((String)cboNumPag.getSelectedItem());
        }
        
        if (paginar==true) {
            tblListCat.setModel(this.CTRL.listar(text, this.totalXPag, this.numPag));
        } else {
            tblListCat.setModel(this.CTRL.listar(text, this.totalXPag, 1));
        }
        
        TableRowSorter orden = new TableRowSorter(tblListCat.getModel());
        tblListCat.setRowSorter(orden);
//        this.ocultarColumna();
        lblRegistros.setText("Mostrando: " + CTRL.totalMostrados() + " registros de " + CTRL.totalReg() + " registros.");
    }
    
    private void limpiar() {
        txtNombre.setText("");
        txtEdad.setText("");
        txtDireccion.setText("");
        txtCuit.setText("");
        txtEmail.setText("");
        this.accion = "guardar";
    }
    
    private void mjeError(String mje) {
        JOptionPane.showMessageDialog(this, mje, "Sistema", JOptionPane.ERROR_MESSAGE);
    }

    private void mjeOK(String mje) {
        JOptionPane.showMessageDialog(this, mje, "Sistema", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCategoria = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListCat = new javax.swing.JTable();
        lblRegistros = new javax.swing.JLabel();
        btnEditarCat = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtNuevoC = new javax.swing.JButton();
        cboNumPag = new javax.swing.JComboBox<>();
        cboTotalXPag = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCuit = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTel1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar cliente:");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblListCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListCat);

        lblRegistros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRegistros.setText("Registros");

        btnEditarCat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarCat.setText("Editar");
        btnEditarCat.setPreferredSize(new java.awt.Dimension(65, 23));
        btnEditarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCatActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButton1.setText("Eliminar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        txtNuevoC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNuevoC.setText("Nuevo");
        txtNuevoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoCActionPerformed(evt);
            }
        });

        cboNumPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNumPagActionPerformed(evt);
            }
        });

        cboTotalXPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "50", "100", "200", "500" }));
        cboTotalXPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTotalXPagActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Registros por pagina:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("N° de paginas:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Seleccionar un cliente de la lista luego precionar \"Seleccionar\":");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("SELECCIONAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addGap(2, 2, 2)
                        .addComponent(btnEditarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNuevoC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(280, 280, 280)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboNumPag, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTotalXPag, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 163, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)
                        .addComponent(btnEditarCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton1))
                    .addComponent(txtNuevoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboNumPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel16)
                        .addComponent(cboTotalXPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelCategoria.addTab("listado", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Los parametros que contenghan (*) son obligatorios");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NUEVO CLIENTES");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Cuit:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Edad:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Direccion:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Email:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tel 1:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtEdad)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDireccion)
                            .addComponent(txtCuit)
                            .addComponent(txtEmail)
                            .addComponent(txtTel1))))
                .addContainerGap(677, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(jButton2))
                .addGap(354, 354, 354))
        );

        panelCategoria.addTab("Administrar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCategoria)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.listar(txtBuscar.getText(),false);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCatActionPerformed
        if (tblListCat.getSelectedRowCount() == 1) {
            String idCliente = String.valueOf(tblListCat.getValueAt(tblListCat.getSelectedRow(), 0));
            String Nombre = String.valueOf(tblListCat.getValueAt(tblListCat.getSelectedRow(), 1));
            String Edad = String.valueOf(tblListCat.getValueAt(tblListCat.getSelectedRow(), 2));
            String Cuit = String.valueOf(tblListCat.getValueAt(tblListCat.getSelectedRow(), 3));
            String Direccion = String.valueOf(tblListCat.getValueAt(tblListCat.getSelectedRow(), 4));
            String Email = String.valueOf(tblListCat.getValueAt(tblListCat.getSelectedRow(), 5));

            txtId.setText(idCliente);
            txtNombre.setText(Nombre);
            txtEdad.setText(Edad);
            txtCuit.setText(Cuit);
            txtDireccion.setText(Direccion);
            txtEmail.setText(Email);
            btnGuardar.setText("Editar");
            panelCategoria.setEnabledAt(0, false);
            panelCategoria.setEnabledAt(1, true);
            panelCategoria.setSelectedIndex(1);
            this.accion = "editar";
        } else {
            this.mjeError("Debe seleccionar un registro");
        }
    }//GEN-LAST:event_btnEditarCatActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (tblListCat.getSelectedRowCount() == 1) {
            String id = String.valueOf(tblListCat.getValueAt(tblListCat.getSelectedRow(), 0));
            String nombre = String.valueOf(tblListCat.getValueAt(tblListCat.getSelectedRow(), 1));

            if (JOptionPane.showConfirmDialog(this, "Deseas eliminar el registro: " + nombre + " ?", "Eliminar", JOptionPane.YES_NO_OPTION) == 0) {
                String resp = this.CTRL.eliminar(Integer.parseInt(id));
                if (resp.equals("OK")) {
                    this.mjeOK("Registro eliminado");
                    this.listar("",false);
                } else {
                    this.mjeError(resp);
                }
            }
        } else {
            this.mjeError("Seleccione 1 registro a desactivar.");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txtNuevoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoCActionPerformed
        this.accion = "guardar";
        btnGuardar.setText("Guardar");
        panelCategoria.setEnabledAt(0, false);
        panelCategoria.setEnabledAt(1, true);
        panelCategoria.setSelectedIndex(1);
    }//GEN-LAST:event_txtNuevoCActionPerformed

    private void cboNumPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNumPagActionPerformed
        if(this.primeraCarga==false){
            this.listar("", true);
        }
    }//GEN-LAST:event_cboNumPagActionPerformed

    private void cboTotalXPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTotalXPagActionPerformed
        this.paginar();
    }//GEN-LAST:event_cboTotalXPagActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String resp;
        if (this.accion.equals("guardar")) {

            if (txtNombre.getText().length() > 100 || txtNombre.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "La marca no debe exceder los 20 caracteres y no debe estar vacia", "sistema", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (txtEdad.getText().length() > 4 || txtEdad.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Nombre no debe exceder los 20 caracteres y no debe estar vacio", "sistema", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (txtDireccion.getText().length() > 100  || txtDireccion.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Cantidad fuera de limites o no se completo el campo", "sistema", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (txtCuit.getText().length() > 45 || txtCuit.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Precio fuera de limites o no se completo el campo", "sistema", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (txtEmail.getText().length() > 45 || txtEmail.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "valor dolar fuera de limites o no se completo el campo", "sistema", JOptionPane.WARNING_MESSAGE);
                return;
            }

            //         int idProd;
            resp = this.CTRL.insertar(txtNombre.getText(), Integer.parseInt(txtEdad.getText()), txtCuit.getText(), txtDireccion.getText(),txtEmail.getText(),txtTel1.getText());
            if (resp.equals("OK")) {
                this.mjeOK("El registro se guardo correctamente");
                this.limpiar();
                panelCategoria.setEnabledAt(1, false);
                panelCategoria.setEnabledAt(0, true);
                panelCategoria.setSelectedIndex(0);
                this.listar("",false);
            } else {
                this.mjeError(resp);

            }
        } else{

            if (txtNombre.getText().length() > 100 || txtNombre.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "La marca no debe exceder los 20 caracteres y no debe estar vacia", "sistema", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (txtEdad.getText().length() > 4 || txtEdad.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Nombre no debe exceder los 20 caracteres y no debe estar vacio", "sistema", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (txtDireccion.getText().length() > 100  || txtDireccion.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Cantidad fuera de limites o no se completo el campo", "sistema", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (txtCuit.getText().length() > 45 || txtCuit.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Precio fuera de limites o no se completo el campo", "sistema", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (txtEmail.getText().length() > 45 || txtEmail.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "valor dolar fuera de limites o no se completo el campo", "sistema", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String nomAnt=txtNombre.getText();
            //         int idProd;
            resp = this.CTRL.actualizar(Integer.parseInt(txtId.getText()),txtNombre.getText(), nomAnt, Integer.parseInt(txtEdad.getText()), txtCuit.getText(), txtDireccion.getText(),txtEmail.getText(),txtTel1.getText());
            if (resp.equals("OK")) {
                this.mjeOK("El registro se guardo correctamente");
                this.limpiar();
                panelCategoria.setEnabledAt(1, false);
                panelCategoria.setEnabledAt(0, true);
                panelCategoria.setSelectedIndex(0);
                this.listar("",false);
            } else {
                this.mjeError(resp);

            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.limpiar();
        this.accion = "guardar";
        panelCategoria.setEnabledAt(1, false);
        panelCategoria.setEnabledAt(0, true);
        panelCategoria.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tblListCat.getSelectedRowCount()==1){
        String id=String.valueOf(tblListCat.getValueAt(tblListCat.getSelectedRow(), 0));
        String nombre=String.valueOf(tblListCat.getValueAt(tblListCat.getSelectedRow(), 1));
        
        this.vista.txtidCliente.setText(id);
        this.vista.txtCliente.setText(nombre);
        this.setVisible(false);
    }else{
        this.mjeError("Debe seleccionar un Cliente");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JToggleButton btnEditarCat;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboNumPag;
    private javax.swing.JComboBox<String> cboTotalXPag;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblRegistros;
    private javax.swing.JTabbedPane panelCategoria;
    private javax.swing.JTable tblListCat;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCuit;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JButton txtNuevoC;
    private javax.swing.JTextField txtTel1;
    // End of variables declaration//GEN-END:variables
}
